wandb_version: 1

_items:
  desc: null
  value:
    _items:
      epochs: 10
      learning_rate: 1.0e-05
      batch_size: 16
      weight_decay: 0.01
      architecture: RoBERTa-base
      dataset: ict
      seed: 42
      _wandb: {}
    _locked: {}
    _users: {}
    _users_inv: {}
    _users_cnt: 0
    _callback: wandb.sdk.wandb_run.Run._config_callback
    _settings:
      _args: null
      _aws_lambda: false
      _async_upload_concurrency_limit: null
      _cli_only_mode: null
      _colab: false
      _cuda: null
      _disable_meta: null
      _disable_service: false
      _disable_setproctitle: false
      _disable_stats: null
      _disable_viewer: null
      _except_exit: null
      _executable: /usr/bin/python
      _extra_http_headers: null
      _flow_control_custom: false
      _flow_control_disabled: false
      _internal_check_process: 8.0
      _internal_queue_timeout: 2.0
      _ipython: false
      _jupyter: true
      _jupyter_name: null
      _jupyter_path: null
      _jupyter_root: null
      _kaggle: false
      _live_policy_rate_limit: null
      _live_policy_wait_time: null
      _log_level: 10
      _network_buffer: null
      _noop: false
      _notebook: true
      _offline: false
      _sync: false
      _os: Linux-5.4.0-137-generic-x86_64-with-glibc2.29
      _platform: linux
      _python: 3.8.10
      _runqueue_item_id: null
      _require_nexus: false
      _save_requirements: true
      _service_transport: null
      _service_wait: 30.0
      _start_datetime: '20230725_123125'
      _start_time: 1690288285.1003332
      _stats_pid: 162274
      _stats_sample_rate_seconds: 2.0
      _stats_samples_to_average: 15
      _stats_join_assets: true
      _stats_neuron_monitor_config_path: null
      _stats_open_metrics_endpoints: null
      _stats_open_metrics_filters:
      - .*
      _tmp_code_dir: /home/work/CL/largecode/wandb/run-20230725_123125-lsowxhvz/tmp/code
      _tracelog: null
      _unsaved_keys: null
      _windows: false
      allow_val_change: null
      anonymous: null
      api_key: null
      azure_account_url_to_access_key: null
      base_url: https://api.wandb.ai
      code_dir: null
      config_paths: null
      console: wrap
      deployment: cloud
      disable_code: null
      disable_git: false
      disable_hints: null
      disable_job_creation: false
      disabled: false
      docker: null
      email: gun9809@gmail.com
      entity: emaeon
      files_dir: /home/work/CL/largecode/wandb/run-20230725_123125-lsowxhvz/files
      force: null
      git_commit: null
      git_remote: origin
      git_remote_url: null
      git_root: null
      heartbeat_seconds: 30
      host: main1
      ignore_globs: []
      init_timeout: 60.0
      is_local: false
      job_name: null
      job_source: null
      label_disable: null
      launch: null
      launch_config_path: null
      log_dir: /home/work/CL/largecode/wandb/run-20230725_123125-lsowxhvz/logs
      log_internal: /home/work/CL/largecode/wandb/run-20230725_123125-lsowxhvz/logs/debug-internal.log
      log_symlink_internal: /home/work/CL/largecode/wandb/debug-internal.log
      log_symlink_user: /home/work/CL/largecode/wandb/debug.log
      log_user: /home/work/CL/largecode/wandb/run-20230725_123125-lsowxhvz/logs/debug.log
      login_timeout: null
      mode: online
      notebook_name: null
      problem: fatal
      program: <python with no main file>
      program_relpath: null
      project: my-awesome-project
      project_url: https://wandb.ai/emaeon/my-awesome-project
      quiet: null
      reinit: null
      relogin: null
      resume: null
      resume_fname: /home/work/CL/largecode/wandb/wandb-resume.json
      resumed: false
      root_dir: /home/work/CL/largecode
      run_group: null
      run_id: lsowxhvz
      run_job_type: null
      run_mode: run
      run_name: grateful-donkey-4
      run_notes: null
      run_tags: null
      run_url: https://wandb.ai/emaeon/my-awesome-project/runs/lsowxhvz
      sagemaker_disable: null
      save_code: null
      settings_system: /home/work/.config/wandb/settings
      settings_workspace: /home/work/CL/largecode/wandb/settings
      show_colors: null
      show_emoji: null
      show_errors: true
      show_info: true
      show_warnings: true
      silent: false
      start_method: null
      strict: null
      summary_errors: null
      summary_timeout: 60
      summary_warnings: 5
      sweep_id: null
      sweep_param_path: null
      sweep_url: ''
      symlink: true
      sync_dir: /home/work/CL/largecode/wandb/run-20230725_123125-lsowxhvz
      sync_file: /home/work/CL/largecode/wandb/run-20230725_123125-lsowxhvz/run-lsowxhvz.wandb
      sync_symlink_latest: /home/work/CL/largecode/wandb/latest-run
      system_sample: 15
      system_sample_seconds: 2
      table_raise_on_max_row_limit_exceeded: false
      timespec: '20230725_123125'
      tmp_dir: /home/work/CL/largecode/wandb/run-20230725_123125-lsowxhvz/tmp
      username: work
      wandb_dir: /home/work/CL/largecode/wandb/
    _artifact_callback: wandb.sdk.wandb_run.Run._config_artifact_callback
    _wandb: {}
_locked:
  desc: null
  value: {}
_users:
  desc: null
  value: {}
_users_inv:
  desc: null
  value: {}
_users_cnt:
  desc: null
  value: 0
_callback:
  desc: null
  value: wandb.sdk.wandb_run.Run._config_callback
_settings:
  desc: null
  value:
    _args: null
    _aws_lambda: false
    _async_upload_concurrency_limit: null
    _cli_only_mode: null
    _colab: false
    _cuda: null
    _disable_meta: null
    _disable_service: false
    _disable_setproctitle: false
    _disable_stats: null
    _disable_viewer: null
    _except_exit: null
    _executable: /usr/bin/python
    _extra_http_headers: null
    _flow_control_custom: false
    _flow_control_disabled: false
    _internal_check_process: 8.0
    _internal_queue_timeout: 2.0
    _ipython: false
    _jupyter: true
    _jupyter_name: null
    _jupyter_path: null
    _jupyter_root: null
    _kaggle: false
    _live_policy_rate_limit: null
    _live_policy_wait_time: null
    _log_level: 10
    _network_buffer: null
    _noop: false
    _notebook: true
    _offline: false
    _sync: false
    _os: Linux-5.4.0-137-generic-x86_64-with-glibc2.29
    _platform: linux
    _python: 3.8.10
    _runqueue_item_id: null
    _require_nexus: false
    _save_requirements: true
    _service_transport: null
    _service_wait: 30.0
    _start_datetime: '20230725_123209'
    _start_time: 1690288329.8120356
    _stats_pid: 162274
    _stats_sample_rate_seconds: 2.0
    _stats_samples_to_average: 15
    _stats_join_assets: true
    _stats_neuron_monitor_config_path: null
    _stats_open_metrics_endpoints: null
    _stats_open_metrics_filters:
    - .*
    _tmp_code_dir: /home/work/CL/largecode/wandb/run-20230725_123209-fhag1d1t/tmp/code
    _tracelog: null
    _unsaved_keys: null
    _windows: false
    allow_val_change: null
    anonymous: null
    api_key: null
    azure_account_url_to_access_key: null
    base_url: https://api.wandb.ai
    code_dir: null
    config_paths: null
    console: wrap
    deployment: cloud
    disable_code: null
    disable_git: false
    disable_hints: null
    disable_job_creation: false
    disabled: false
    docker: null
    email: gun9809@gmail.com
    entity: emaeon
    files_dir: /home/work/CL/largecode/wandb/run-20230725_123209-fhag1d1t/files
    force: null
    git_commit: null
    git_remote: origin
    git_remote_url: null
    git_root: null
    heartbeat_seconds: 30
    host: main1
    ignore_globs: []
    init_timeout: 60.0
    is_local: false
    job_name: null
    job_source: null
    label_disable: null
    launch: null
    launch_config_path: null
    log_dir: /home/work/CL/largecode/wandb/run-20230725_123209-fhag1d1t/logs
    log_internal: /home/work/CL/largecode/wandb/run-20230725_123209-fhag1d1t/logs/debug-internal.log
    log_symlink_internal: /home/work/CL/largecode/wandb/debug-internal.log
    log_symlink_user: /home/work/CL/largecode/wandb/debug.log
    log_user: /home/work/CL/largecode/wandb/run-20230725_123209-fhag1d1t/logs/debug.log
    login_timeout: null
    mode: online
    notebook_name: null
    problem: fatal
    program: <python with no main file>
    program_relpath: null
    project: my-awesome-project
    project_url: https://wandb.ai/emaeon/my-awesome-project
    quiet: null
    reinit: null
    relogin: null
    resume: null
    resume_fname: /home/work/CL/largecode/wandb/wandb-resume.json
    resumed: false
    root_dir: /home/work/CL/largecode
    run_group: null
    run_id: fhag1d1t
    run_job_type: null
    run_mode: run
    run_name: olive-river-5
    run_notes: null
    run_tags: null
    run_url: https://wandb.ai/emaeon/my-awesome-project/runs/fhag1d1t
    sagemaker_disable: null
    save_code: null
    settings_system: /home/work/.config/wandb/settings
    settings_workspace: /home/work/CL/largecode/wandb/settings
    show_colors: null
    show_emoji: null
    show_errors: true
    show_info: true
    show_warnings: true
    silent: false
    start_method: null
    strict: null
    summary_errors: null
    summary_timeout: 60
    summary_warnings: 5
    sweep_id: null
    sweep_param_path: null
    sweep_url: ''
    symlink: true
    sync_dir: /home/work/CL/largecode/wandb/run-20230725_123209-fhag1d1t
    sync_file: /home/work/CL/largecode/wandb/run-20230725_123209-fhag1d1t/run-fhag1d1t.wandb
    sync_symlink_latest: /home/work/CL/largecode/wandb/latest-run
    system_sample: 15
    system_sample_seconds: 2
    table_raise_on_max_row_limit_exceeded: false
    timespec: '20230725_123209'
    tmp_dir: /home/work/CL/largecode/wandb/run-20230725_123209-fhag1d1t/tmp
    username: work
    wandb_dir: /home/work/CL/largecode/wandb/
_artifact_callback:
  desc: null
  value: wandb.sdk.wandb_run.Run._config_artifact_callback
_wandb:
  desc: null
  value:
    python_version: 3.8.10
    cli_version: 0.15.6
    framework: huggingface
    huggingface_version: 4.31.0
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1690288370.424901
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 53
      - 55
      - 71
      2:
      - 1
      - 5
      - 11
      - 49
      - 53
      - 55
      - 71
      3:
      - 1
      - 16
      - 23
      4: 3.8.10
      5: 0.15.6
      6: 4.31.0
      8:
      - 1
      - 5
